/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.curso.open.swing.view;

import br.com.curso.open.swing.controller.FuncionarioGridController;
import br.com.curso.open.swing.util.Util;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;
import org.openswing.swing.client.GridControl;
import org.openswing.swing.lookup.client.LookupController;

/**
 *
 * @author jonat
 */
public class FuncionarioView extends javax.swing.JFrame {

    /**
     * Creates new form FuncionarioView
     */
    public FuncionarioView() {

        initComponents();

        this.organizarDomain();
        this.organizarMascaras();
        this.organizarLookup();
        this.organizarFiltro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        editButton1 = new org.openswing.swing.client.EditButton();
        editLoteButton1 = new org.openswing.swing.client.EditLoteButton();
        deleteButton1 = new org.openswing.swing.client.DeleteButton();
        saveButton1 = new org.openswing.swing.client.SaveButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        filterButton1 = new org.openswing.swing.client.FilterButton();
        filtroGridControl1 = new br.com.sisaudcon.filtroGridControl.visao.filtroGridControl();
        jPanel2 = new javax.swing.JPanel();
        gridControlFuncionario = new org.openswing.swing.client.GridControl();
        textColumnNome = new org.openswing.swing.table.columns.client.TextColumn();
        comboColumnSexo = new org.openswing.swing.table.columns.client.ComboColumn();
        currencyColumnSalario = new org.openswing.swing.table.columns.client.CurrencyColumn();
        dateColumnEntrada = new org.openswing.swing.table.columns.client.DateColumn();
        dateColumnSaida = new org.openswing.swing.table.columns.client.DateColumn();
        textColumnCidade = new org.openswing.swing.table.columns.client.TextColumn();
        textColumnLogradouro = new org.openswing.swing.table.columns.client.TextColumn();
        textColumnNumero = new org.openswing.swing.table.columns.client.TextColumn();
        textColumnComplemento = new org.openswing.swing.table.columns.client.TextColumn();
        textColumnBairro = new org.openswing.swing.table.columns.client.TextColumn();
        comboColumnUf = new org.openswing.swing.table.columns.client.ComboColumn();
        formattedTextColumnCep = new org.openswing.swing.table.columns.client.FormattedTextColumn();
        codLookupColumnCargo = new org.openswing.swing.table.columns.client.CodLookupColumn();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Funcionário");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(225, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(40, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(40, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(insertButton1);
        jPanel1.add(editButton1);
        jPanel1.add(editLoteButton1);
        jPanel1.add(deleteButton1);
        jPanel1.add(saveButton1);
        jPanel1.add(reloadButton1);
        jPanel1.add(filterButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(filtroGridControl1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(225, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(40, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(40, 40));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        gridControlFuncionario.setDeleteButton(this.deleteButton1);
        gridControlFuncionario.setEditButton(this.editButton1);
        gridControlFuncionario.setEditLoteButton(this.editLoteButton1);
        gridControlFuncionario.setFilterButton(this.filterButton1);
        gridControlFuncionario.setInsertButton(this.insertButton1);
        gridControlFuncionario.setMaxNumberOfRowsOnInsert(10);
        gridControlFuncionario.setReloadButton(this.reloadButton1);
        gridControlFuncionario.setSaveButton(this.saveButton1);
        gridControlFuncionario.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControlFuncionario.setValueObjectClassName("br.com.curso.open.swing.vo.FuncionarioVO");

        textColumnNome.setColumnFilterable(true);
        textColumnNome.setColumnName("nome");
        textColumnNome.setColumnSortable(true);
        textColumnNome.setEditableOnEdit(true);
        textColumnNome.setEditableOnInsert(true);
        textColumnNome.setHeaderColumnName("Nome");
        gridControlFuncionario.getColumnContainer().add(textColumnNome);

        comboColumnSexo.setColumnFilterable(true);
        comboColumnSexo.setColumnName("sexo");
        comboColumnSexo.setColumnSortable(true);
        comboColumnSexo.setEditableOnEdit(true);
        comboColumnSexo.setEditableOnInsert(true);
        comboColumnSexo.setHeaderColumnName("Sexo");
        gridControlFuncionario.getColumnContainer().add(comboColumnSexo);

        currencyColumnSalario.setColumnFilterable(true);
        currencyColumnSalario.setColumnName("salario");
        currencyColumnSalario.setColumnRequired(false);
        currencyColumnSalario.setColumnSortable(true);
        currencyColumnSalario.setEditableOnEdit(true);
        currencyColumnSalario.setEditableOnInsert(true);
        currencyColumnSalario.setHeaderColumnName("Salário");
        gridControlFuncionario.getColumnContainer().add(currencyColumnSalario);

        dateColumnEntrada.setColumnFilterable(true);
        dateColumnEntrada.setColumnName("data_de_entrada");
        dateColumnEntrada.setColumnSortable(true);
        dateColumnEntrada.setEditableOnEdit(true);
        dateColumnEntrada.setEditableOnInsert(true);
        dateColumnEntrada.setHeaderColumnName("Data de Entrada");
        gridControlFuncionario.getColumnContainer().add(dateColumnEntrada);

        dateColumnSaida.setColumnFilterable(true);
        dateColumnSaida.setColumnName("data_de_saida");
        dateColumnSaida.setColumnRequired(false);
        dateColumnSaida.setColumnSortable(true);
        dateColumnSaida.setEditableOnEdit(true);
        dateColumnSaida.setEditableOnInsert(true);
        dateColumnSaida.setHeaderColumnName("Data de Saída");
        gridControlFuncionario.getColumnContainer().add(dateColumnSaida);

        textColumnCidade.setColumnFilterable(true);
        textColumnCidade.setColumnName("cidade");
        textColumnCidade.setColumnSortable(true);
        textColumnCidade.setEditableOnEdit(true);
        textColumnCidade.setEditableOnInsert(true);
        textColumnCidade.setHeaderColumnName("Cidade");
        gridControlFuncionario.getColumnContainer().add(textColumnCidade);

        textColumnLogradouro.setColumnFilterable(true);
        textColumnLogradouro.setColumnName("logradouro");
        textColumnLogradouro.setColumnSortable(true);
        textColumnLogradouro.setEditableOnEdit(true);
        textColumnLogradouro.setEditableOnInsert(true);
        gridControlFuncionario.getColumnContainer().add(textColumnLogradouro);

        textColumnNumero.setColumnFilterable(true);
        textColumnNumero.setColumnName("numero");
        textColumnNumero.setColumnRequired(false);
        textColumnNumero.setColumnSortable(true);
        textColumnNumero.setEditableOnEdit(true);
        textColumnNumero.setEditableOnInsert(true);
        gridControlFuncionario.getColumnContainer().add(textColumnNumero);

        textColumnComplemento.setColumnFilterable(true);
        textColumnComplemento.setColumnName("complemento");
        textColumnComplemento.setColumnRequired(false);
        textColumnComplemento.setColumnSortable(true);
        textColumnComplemento.setEditableOnEdit(true);
        textColumnComplemento.setEditableOnInsert(true);
        gridControlFuncionario.getColumnContainer().add(textColumnComplemento);

        textColumnBairro.setColumnFilterable(true);
        textColumnBairro.setColumnName("bairro");
        textColumnBairro.setColumnSortable(true);
        textColumnBairro.setEditableOnEdit(true);
        textColumnBairro.setEditableOnInsert(true);
        gridControlFuncionario.getColumnContainer().add(textColumnBairro);

        comboColumnUf.setColumnFilterable(true);
        comboColumnUf.setColumnName("uf");
        comboColumnUf.setColumnSortable(true);
        comboColumnUf.setEditableOnEdit(true);
        comboColumnUf.setEditableOnInsert(true);
        comboColumnUf.setHeaderColumnName("UF");
        gridControlFuncionario.getColumnContainer().add(comboColumnUf);

        formattedTextColumnCep.setColumnFilterable(true);
        formattedTextColumnCep.setColumnName("cep");
        formattedTextColumnCep.setColumnRequired(false);
        formattedTextColumnCep.setColumnSortable(true);
        formattedTextColumnCep.setEditableOnEdit(true);
        formattedTextColumnCep.setEditableOnInsert(true);
        gridControlFuncionario.getColumnContainer().add(formattedTextColumnCep);

        codLookupColumnCargo.setColumnFilterable(true);
        codLookupColumnCargo.setColumnName("cargo");
        codLookupColumnCargo.setColumnRequired(false);
        codLookupColumnCargo.setColumnSortable(true);
        codLookupColumnCargo.setEditableOnEdit(true);
        codLookupColumnCargo.setEditableOnInsert(true);
        gridControlFuncionario.getColumnContainer().add(codLookupColumnCargo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(gridControlFuncionario, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        setSize(new java.awt.Dimension(1018, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            new Principal(new Login());
            new FuncionarioGridController();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.CodLookupColumn codLookupColumnCargo;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumnSexo;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumnUf;
    private org.openswing.swing.table.columns.client.CurrencyColumn currencyColumnSalario;
    private org.openswing.swing.table.columns.client.DateColumn dateColumnEntrada;
    private org.openswing.swing.table.columns.client.DateColumn dateColumnSaida;
    private org.openswing.swing.client.DeleteButton deleteButton1;
    private org.openswing.swing.client.EditButton editButton1;
    private org.openswing.swing.client.EditLoteButton editLoteButton1;
    private org.openswing.swing.client.FilterButton filterButton1;
    private br.com.sisaudcon.filtroGridControl.visao.filtroGridControl filtroGridControl1;
    private org.openswing.swing.table.columns.client.FormattedTextColumn formattedTextColumnCep;
    private org.openswing.swing.client.GridControl gridControlFuncionario;
    private org.openswing.swing.client.InsertButton insertButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.client.SaveButton saveButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumnBairro;
    private org.openswing.swing.table.columns.client.TextColumn textColumnCidade;
    private org.openswing.swing.table.columns.client.TextColumn textColumnComplemento;
    private org.openswing.swing.table.columns.client.TextColumn textColumnLogradouro;
    private org.openswing.swing.table.columns.client.TextColumn textColumnNome;
    private org.openswing.swing.table.columns.client.TextColumn textColumnNumero;
    // End of variables declaration//GEN-END:variables

    private void organizarDomain() {
        this.comboColumnSexo.setDomainId("SEXO");
        this.comboColumnUf.setDomainId("UF");
    }

    private void organizarMascaras() {
        try {
            MaskFormatter mascara = new MaskFormatter("##.###-###");
            mascara.setPlaceholderCharacter('_');
            mascara.setValidCharacters("0123456789");
            this.formattedTextColumnCep.setFormatter(mascara);
        } catch (ParseException ex) {
            Logger.getLogger(FuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void organizarLookup() {
        this.codLookupColumnCargo.setLookupController(new LookupController());
    }

    public GridControl getGridControlFuncionario() {
        return gridControlFuncionario;
    }

    private void organizarFiltro() {
        this.filtroGridControl1.setColunas(Util.carregarColunas(gridControlFuncionario));
        this.filtroGridControl1.setGridControl(gridControlFuncionario);
        this.filtroGridControl1.setPesquisarAoDigitar(true);
    }
}
